
import { Offence, OffenceCategory, OffenceType } from './types';

export const OFFENCES: Offence[] = [
  // ==========================================
  // ALL JAILABLE OFFENCES (CRIMINAL & TRAFFIC)
  // ==========================================
  { id: "j1", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1110", name: "Murder", punishment: 300, act: "Crimes Act 1961 167" },
  { id: "j2", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1120", name: "Attempted Murder", punishment: 250, act: "Crimes Act 1961 173" },
  { id: "j3", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1130", name: "Manslaughter", punishment: 200, act: "Crimes Act 1961 171" },
  { id: "j4", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1210", name: "Kidnapping/Abduction", punishment: 250, act: "Crimes Act 1961 209" },
  { id: "j5", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1310", name: "Aggravated Robbery (Weapon)", punishment: 200, act: "Crimes Act 1961 235" },
  { id: "j6", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1316", name: "Aggravated Robbery (Manual)", punishment: 150, act: "Crimes Act 1961 235" },
  { id: "j7", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1320", name: "Robbery", punishment: 120, act: "Crimes Act 1961 234" },
  { id: "j8", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1410", name: "Grievous Assault", punishment: 250, act: "Crimes Act 1961 188" },
  { id: "j9", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1510", name: "Serious Assault", punishment: 150, act: "Crimes Act 1961 189" },
  { id: "j10", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1640", name: "Minor Assault", punishment: 60, act: "Summary Offences Act 1981 9" },
  { id: "j11", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1710", name: "Threats/Intimidation", punishment: 120, act: "Crimes Act 1961 306" },
  { id: "j12", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1540", name: "Male Assaults Female", punishment: 150, act: "Crimes Act 1961 194" },
  { id: "j13", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1480", name: "Use firearm on Police Officer", punishment: 200, act: "Arms Act 1983 54" },
  { id: "j14", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1550", name: "Assaults Police", punishment: 150, act: "Summary Offences Act 1981 10" },
  { id: "j15", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "6340", name: "Injures Police Dog", punishment: 200, act: "Police Act 2008 33" },
  { id: "j16", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "6820", name: "Firearms Offences (General)", punishment: 150, act: "Arms Act 1983 44" },
  { id: "j17", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "6851", name: "Unlawfully Carries/Possess Firearm/Explosives", punishment: 150, act: "Arms Act 1983 45" },
  { id: "j18", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "6852", name: "Unlawfully Carries imitation Firearm", punishment: 100, act: "Arms Act 1983 46" },
  { id: "j19", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "6853", name: "Intoxicated in Charge of firearm", punishment: 120, act: "Arms Act 1983 48" },
  { id: "j20", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "6854", name: "Discharges Firearm in/near place/dwelling", punishment: 100, act: "Arms Act 1983 44" },
  { id: "j21", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "6856", name: "Unlawful possess pistol or Restricted weapon", punishment: 100, act: "Arms Act 1983 50" },
  { id: "j22", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "3510", name: "Obstructs Police", punishment: 80, act: "Summary Offences Act 1981 23" },
  { id: "j23", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1710", name: "Threatens to Kill", punishment: 100, act: "Crimes Act 1961 306" },
  { id: "j24", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1730", name: "Threatening Behaviour", punishment: 80, act: "Summary Offences Act 1981 3" },
  { id: "j25", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1754", name: "Possess Offensive Weapon", punishment: 100, act: "Crimes Act 1961 202A" },
  { id: "j26", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1758", name: "Unlawful possess knife", punishment: 80, act: "Crimes Act 1961 202A" },
  { id: "j27", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1790", name: "Threatening to Damage Property", punishment: 80, act: "Crimes Act 1961 307" },
  { id: "j28", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1820", name: "Unlawful Assembly", punishment: 60, act: "Crimes Act 1961 86" },
  { id: "j29", type: OffenceType.JAIL, category: OffenceCategory.LIQUOR_DRUGS, code: "3110", name: "Import, Supply or Produce Class A Drug", punishment: 120, act: "Misuse of Drugs Act 1975 6" },
  { id: "j30", type: OffenceType.JAIL, category: OffenceCategory.LIQUOR_DRUGS, code: "3115", name: "Import, Supply or Produce Class B Drug", punishment: 100, act: "Misuse of Drugs Act 1975 6" },
  { id: "j31", type: OffenceType.JAIL, category: OffenceCategory.LIQUOR_DRUGS, code: "3210", name: "Import, Supply or Produce Class C Drug", punishment: 80, act: "Misuse of Drugs Act 1975 6" },
  { id: "j32", type: OffenceType.JAIL, category: OffenceCategory.LIQUOR_DRUGS, code: "3151", name: "Possess Class A Drug", punishment: 80, act: "Misuse of Drugs Act 1975 7" },
  { id: "j33", type: OffenceType.JAIL, category: OffenceCategory.LIQUOR_DRUGS, code: "3154", name: "Possess Class B Drug", punishment: 70, act: "Misuse of Drugs Act 1975 7" },
  { id: "j34", type: OffenceType.JAIL, category: OffenceCategory.LIQUOR_DRUGS, code: "3150", name: "Possess Class C Drug", punishment: 60, act: "Misuse of Drugs Act 1975 7" },
  { id: "j35", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "3521", name: "Incite Violence, disorder or lawlessness", punishment: 100, act: "Summary Offences Act 1981 12" },
  { id: "j36", type: OffenceType.JAIL, category: OffenceCategory.DISORDER, code: "3535", name: "Offensive Behaviours", punishment: 80, act: "Summary Offences Act 1981 4" },
  { id: "j37", type: OffenceType.JAIL, category: OffenceCategory.DISORDER, code: "3537", name: "Disorderly Behaviour (Private Premises)", punishment: 80, act: "Summary Offences Act 1981 3" },
  { id: "j38", type: OffenceType.JAIL, category: OffenceCategory.DISORDER, code: "3560", name: "Miscellaneous Disorder Offences", punishment: 80, act: "Summary Offences Act 1981 4" },
  { id: "j39", type: OffenceType.JAIL, category: OffenceCategory.LIQUOR_DRUGS, code: "3985", name: "Breach of Council Liquor Ban", punishment: 80, act: "Local Government Act 2002 147" },
  { id: "j40", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "3850", name: "Contravenes Protection Order", punishment: 100, act: "Family Violence Act 2018 112" },
  { id: "j41", type: OffenceType.JAIL, category: OffenceCategory.LIQUOR_DRUGS, code: "3920", name: "Licensed Premises Liquor Offence (Minors)", punishment: 80, act: "Sale and Supply of Alcohol Act 2012 243" },
  { id: "j42", type: OffenceType.JAIL, category: OffenceCategory.LIQUOR_DRUGS, code: "3950", name: "Refusal to administer Police on Licensed Premises", punishment: 60, act: "Sale and Supply of Alcohol Act 2012 268" },
  { id: "j43", type: OffenceType.JAIL, category: OffenceCategory.LIQUOR_DRUGS, code: "3970", name: "Unlicensed Premises Liquor Offences", punishment: 60, act: "Sale and Supply of Alcohol Act 2012 235" },
  { id: "j44", type: OffenceType.JAIL, category: OffenceCategory.DISHONESTY, code: "4120", name: "Burglary", punishment: 150, act: "Crimes Act 1961 231" },
  { id: "j45", type: OffenceType.JAIL, category: OffenceCategory.DISHONESTY, code: "4155", name: "Aggravated Burglary", punishment: 200, act: "Crimes Act 1961 232" },
  { id: "j46", type: OffenceType.JAIL, category: OffenceCategory.DISHONESTY, code: "4211", name: "Unlawful Taking Motor Vehicle", punishment: 120, act: "Crimes Act 1961 226" },
  { id: "j47", type: OffenceType.JAIL, category: OffenceCategory.DISHONESTY, code: "4220", name: "Unlawfully Interfere with Motor Vehicle", punishment: 100, act: "Summary Offences Act 1981 11" },
  { id: "j48", type: OffenceType.JAIL, category: OffenceCategory.DISHONESTY, code: "4230", name: "Take, Convert or Interfere with Bicycle", punishment: 80, act: "Summary Offences Act 1981 11" },
  { id: "j49", type: OffenceType.JAIL, category: OffenceCategory.DISHONESTY, code: "4320", name: "Theft ex Shop", punishment: 60, act: "Crimes Act 1961 219" },
  { id: "j50", type: OffenceType.JAIL, category: OffenceCategory.DISHONESTY, code: "4370", name: "General Theft", punishment: 60, act: "Crimes Act 1961 219" },
  { id: "j51", type: OffenceType.JAIL, category: OffenceCategory.DISHONESTY, code: "4378", name: "Theft of Boat", punishment: 120, act: "Crimes Act 1961 219" },
  { id: "j52", type: OffenceType.JAIL, category: OffenceCategory.DISHONESTY, code: "4530", name: "Fraud", punishment: 120, act: "Crimes Act 1961 240" },
  { id: "j53", type: OffenceType.JAIL, category: OffenceCategory.PROPERTY, code: "5110", name: "Arson", punishment: 150, act: "Crimes Act 1961 267" },
  { id: "j54", type: OffenceType.JAIL, category: OffenceCategory.PROPERTY, code: "5113", name: "Attempted Arson", punishment: 100, act: "Crimes Act 1961 267" },
  { id: "j55", type: OffenceType.JAIL, category: OffenceCategory.PROPERTY, code: "5120", name: "Wilful Damage", punishment: 120, act: "Crimes Act 1961 269" },
  { id: "j56", type: OffenceType.JAIL, category: OffenceCategory.PROPERTY, code: "5210", name: "Endangering/Interfering", punishment: 90, act: "Crimes Act 1961 270" },
  { id: "j57", type: OffenceType.JAIL, category: OffenceCategory.PROPERTY, code: "5232", name: "Endangering Safety of Plane", punishment: 150, act: "Civil Aviation Act 1990 12" },
  { id: "j58", type: OffenceType.JAIL, category: OffenceCategory.PROPERTY, code: "5235", name: "Endangering Safety in Airport", punishment: 150, act: "Civil Aviation Act 1990 13" },
  { id: "j59", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "6110", name: "Offences under Trespass Act", punishment: 100, act: "Trespass Act 1980 3" },
  { id: "j60", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "6210", name: "Littering (Serious)", punishment: 15, act: "Litter Act 1979 15" },
  { id: "j61", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "1840", name: "Harassment", punishment: 80, act: "Harassment Act 1997 8" },
  { id: "j62", type: OffenceType.JAIL, category: OffenceCategory.MISC, code: "6333", name: "Breach Of Fisheries Act", punishment: 100, act: "Fisheries Act 1996 252" },
  { id: "j63", type: OffenceType.JAIL, category: OffenceCategory.MISC, code: "6391", name: "Cruelty to or Ill-treatment of Animals", punishment: 100, act: "Animal Welfare Act 1999 28" },
  { id: "j64", type: OffenceType.JAIL, category: OffenceCategory.MISC, code: "6530", name: "Fire Service Abuses", punishment: 100, act: "FENZ Act 2017 48" },
  { id: "j65", type: OffenceType.JAIL, category: OffenceCategory.MISC, code: "6550", name: "Telecommunications Act Offences", punishment: 60, act: "Telecommunications Act 2001 112" },
  { id: "j66", type: OffenceType.JAIL, category: OffenceCategory.MISC, code: "7125", name: "Obstruct/Pervert/Defeat Course of Justice", punishment: 100, act: "Crimes Act 1961 116" },
  { id: "j67", type: OffenceType.JAIL, category: OffenceCategory.MISC, code: "7130", name: "Escapes Custody", punishment: 200, act: "Crimes Act 1961 120" },
  { id: "j68", type: OffenceType.JAIL, category: OffenceCategory.CRIMINAL, code: "7510", name: "Treason", punishment: 300, act: "Crimes Act 1961 73" },
  { id: "j69", type: OffenceType.JAIL, category: OffenceCategory.MISC, code: "6D", name: "Bail Breach", punishment: 80, act: "Bail Act 2000 35" },
  { id: "j70", type: OffenceType.JAIL, category: OffenceCategory.TRAFFIC, code: "FTS", name: "Failed to Stop for Red/Blue", punishment: 120, act: "Land Transport Act 1998 114" },
  { id: "j71", type: OffenceType.JAIL, category: OffenceCategory.TRAFFIC, code: "FRS", name: "Failed to Remain Stopped", punishment: 120, act: "Land Transport Act 1998 114" },
  { id: "j72", type: OffenceType.JAIL, category: OffenceCategory.TRAFFIC, code: "FPP", name: "Failed to Provide Particulars", punishment: 60, act: "Land Transport Act 1998 113" },
  { id: "j73", type: OffenceType.JAIL, category: OffenceCategory.TRAFFIC, code: "EBA", name: "Breath Alcohol Exceeds 400mcg", punishment: 100, act: "Land Transport Act 1998 56" },
  { id: "j74", type: OffenceType.JAIL, category: OffenceCategory.TRAFFIC, code: "DDM", name: "Driving in a Dangerous Manner", punishment: 100, act: "Land Transport Act 1998 35" },
  { id: "j75", type: OffenceType.JAIL, category: OffenceCategory.TRAFFIC, code: "DWD", name: "Driving while Disqualified", punishment: 100, act: "Land Transport Act 1998 32" },
  { id: "j76", type: OffenceType.JAIL, category: OffenceCategory.TRAFFIC, code: "CD-D", name: "Careless Driving causing Death", punishment: 300, act: "Land Transport Act 1998 37" },
  { id: "j77", type: OffenceType.JAIL, category: OffenceCategory.TRAFFIC, code: "CD-I", name: "Careless Driving causing Injury", punishment: 150, act: "Land Transport Act 1998 38" },
   { id: "j78", type: OffenceType.JAIL, category: OffenceCategory.MISC, code: "GIPO", name: "Breach of Gangs Act 2024", punishment: 80, notes: "Immediate seizure of any clothing, Item or vehicle displaying gang insignia" },

  // ==========================================
  // ALL FINEABLE OFFENCES
  // ==========================================
  { id: "f1", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "SPD", name: "SPEEDING - + <10km/h", punishment: 30, demerits: 10, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f2", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "SPD", name: "SPEEDING - + 11-15km/h", punishment: 80, demerits: 20, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f3", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "SPD", name: "SPEEDING - + 16-20km/h", punishment: 120, demerits: 20, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f4", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "SPD", name: "SPEEDING - + 21-25km/h", punishment: 170, demerits: 35, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f5", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "SPD", name: "SPEEDING - + 26-30km/h", punishment: 230, demerits: 35, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f6", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "SPD", name: "SPEEDING - + 31-35km/h", punishment: 300, demerits: 40, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f7", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "SPD", name: "SPEEDING - + 36-40km/h", punishment: 400, demerits: 50, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f8", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "SPD", name: "SPEEDING - + 41-45km/h", punishment: 510, demerits: 50, act: "Land Transport (Road User) Rule 2004 2.1", notes: "<40km/h incurs 28 Day Licence Suspension" },
  { id: "f9", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "SPD", name: "SPEEDING - + 46-50km/h", punishment: 630, demerits: 50, act: "Land Transport (Road User) Rule 2004 2.1", notes: "<40km/h incurs 28 Day Licence Suspension" },
  { id: "f10", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "SPD", name: "SPEEDING - + >50km/h", punishment: 630, demerits: 50, act: "Land Transport (Road User) Rule 2004 2.1", notes: "<50km/h incurs 28 Day Licence Suspension" },
  { id: "f11", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "B113", name: "INTERFERED WITH NON-OPERATION ORDER AFFIXED TO VEHICLE", punishment: 600, act: "Land Transport Act 1998 115", notes: "Removing green or pink sticker off vehicle" },
  { id: "f12", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "B118", name: "DROVE VEHICLE ISSUED WITH NON-OPERATION ORDER", punishment: 600, act: "Land Transport Act 1998 115", notes: "Driving vehicle with green or pink sticker" },
  { id: "f13", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "C101", name: "NO EVIDENCE OF INSPECTION - PRIVATE VEHICLE", punishment: 200, act: "Land Transport Act 1998 242" },
  { id: "f14", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "C108", name: "NOT UP TO WARRANT OF FITNESS STANDARD", punishment: 200, act: "Land Transport Act 1998 242" },
  { id: "f15", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "C201", name: "NO EVIDENCE OF INSPECTION - COMMERCIAL VEHICLE", punishment: 600, act: "Land Transport Act 1998 242" },
  { id: "f16", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "C208", name: "NOT UP TO CERTIFICATE OF FITNESS STANDARD", punishment: 150, act: "Land Transport Act 1998 242" },
  { id: "f17", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "B106", name: "GAVE FALSE DETAILS AS TO OWN IDENTITY", punishment: 750, act: "Land Transport Act 1998 113" },
  { id: "f18", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "B107", name: "GAVE FALSE DETAILS AS TO DRIVER IDENTITY", punishment: 750, act: "Land Transport Act 1998 113" },
  { id: "f19", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "B208", name: "FAILED TO REPORT DAMAGE TO VEHICLE OR PROPERTY", punishment: 370, act: "Land Transport Act 1998 22" },
  { id: "f20", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "H128", name: "EXCEEDED MAX DISTANCE LICENCE - LIGHT RUC", punishment: 200, act: "Road User Charges Act 2012 37" },
  { id: "f21", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "H129", name: "EXCEEDED MAX DISTANCE LICENCE - HEAVY RUC", punishment: 300, act: "Road User Charges Act 2012 37", notes: "Scale $300 - $1500" },
  { id: "f22", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L452", name: "OPERATED AN UNREGISTERED MOTOR VEHICLE", punishment: 150, demerits: 20, act: "Land Transport Act 1998 242" },
  { id: "f23", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L453", name: "OPERATED AN UNLICENCED MOTOR VEHICLE", punishment: 100, demerits: 15, act: "Land Transport Act 1998 242" },
  { id: "f24", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L455", name: "CURRENT LICENCE LABEL AFFIXED IN PRESCRIBED MANNER", punishment: 75, act: "Land Transport Act 1998 242" },
  { id: "f25", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L469", name: "DISPLAYED OTHER THAN AUTHORISED MOTOR VEHICLE LICENCE", punishment: 100, demerits: 25, act: "Land Transport Act 1998 242" },
  { id: "f26", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L473", name: "DROVE VEHICLE WITH TEMPORARY EXEMPTION", punishment: 150, demerits: 20, act: "Land Transport Act 1998 242" },
  { id: "f27", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L454", name: "REGISTRATION PLATES NOT AFFIXED IN PRESCRIBED MANNER", punishment: 150, demerits: 20, act: "Land Transport Act 1998 242" },
  { id: "f28", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L468", name: "DISPLAYED OTHER THAN AUTHORISED REGISTRATION PLATE", punishment: 100, demerits: 25, act: "Land Transport Act 1998 242" },
  { id: "f29", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L471", name: "OBSCURED OR INDISTINGUISHABLE REGISTRATION PLATE", punishment: 100, demerits: 25, act: "Land Transport Act 1998 242" },
  { id: "f30", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "M401", name: "DRIVER OR PASSENGER NOT WEARING SAFETY BELT CORRECTLY", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.7" },
  { id: "f31", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N323", name: "CARRIED PASSENGER IN A CARAVAN", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.10" },
  { id: "f32", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O301", name: "PERMITTED RIDING ON MOTOR VEHICLE IN DANGEROUS POSITION", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 7.9" },
  { id: "f33", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O302", name: "RODE ON A MOTOR VEHICLE IN A DANGEROUS POSITION", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.9" },
  { id: "f34", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L114", name: "FAILED TO PRODUCE DRIVER LICENCE", punishment: 55, act: "Land Transport Act 1998 113" },
  { id: "f35", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L122", name: "DROVE CONTRARY TO CONDITIONS OF DRIVER LICENCE", punishment: 400, demerits: 25, act: "Land Transport Act 1998 31" },
  { id: "f36", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L129", name: "AIDED OR ABETTED AN UNLICENCED DRIVER TO DRIVE", punishment: 400, act: "Land Transport Act 1998 31" },
  { id: "f37", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L144", name: "DROVE WITHOUT APPROPRIATE DRIVER LICENCE", punishment: 400, act: "Land Transport Act 1998 31" },
  { id: "f38", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L148", name: "AIDED OR ABETTED DRIVER WITH EXPIRED LICENCE", punishment: 400, act: "Land Transport Act 1998 31" },
  { id: "f39", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L149", name: "DROVE WITH AN EXPIRED DRIVER LICENCE", punishment: 400, act: "Land Transport Act 1998 31" },
  { id: "f40", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L536", name: "DROVE IN BREACH OF AUTO TRANS CONDITION", punishment: 100, act: "Land Transport Act 1998 31" },
  { id: "f41", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L504", name: "LEARNER DRIVER UNACCOMPANIED", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f42", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L505", name: "LEARNER'S OVERSEER HELD FULL LICENCE < 2 YRS", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f43", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L507", name: "LEARNER'S OVERSEER NOT SEATED NEAR AS PRACTICABLE", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f44", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L518", name: "LEARNER RIDER RODE OTHER THAN APPROVED MOTORCYCLE", punishment: 100, act: "Land Transport Act 1998 31" },
  { id: "f45", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L510", name: "LEARNER RODE MOTO/MOPED 10PM-5AM", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f46", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L511", name: "LEARNER CARRIED PILLION PASSENGER", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f47", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L514", name: "LEARNER LICENCEE FAILED TO DISPLAY AN L-PLATE", punishment: 100, demerits: 25, act: "Land Transport Act 1998 31" },
  { id: "f48", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L515", name: "AIDED LEARNER TO DRIVE UNACCOMPANIED", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f49", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L523", name: "RESTRICTED DRIVER UNACCOMPANIED 10PM-5AM", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f50", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L524", name: "RESTRICTED DRIVER'S OVERSEER < 2 YRS", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f51", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L526", name: "RESTRICTED DRIVER'S OVERSEER NOT SEATED NEXT", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f52", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L555", name: "RESTRICTED RIDER RODE OTHER THAN APPROVED MOTO", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f53", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L528", name: "RESTRICTED DRIVER RODE MOTO 10PM-5AM", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f54", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L529", name: "RESTRICTED DRIVER CARRIED PILLION PASSENGER", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f55", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L531", name: "RESTRICTED DRIVER CARRIED UNAUTHORISED PASSENGER", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f56", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L533", name: "AIDED RESTRICTED UNACCOMPANIED 10PM-5AM", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f57", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "L535", name: "AIDED RESTRICTED TO DRIVE WITH UNQUALIFIED OVERSEER", punishment: 100, demerits: 35, act: "Land Transport Act 1998 31" },
  { id: "f58", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O101", name: "RODE A CYCLE MORE THAN TWO ABREAST", punishment: 55, act: "Land Transport (Road User) Rule 2004 11.1" },
  { id: "f59", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O501", name: "FAILED TO WEAR CYCLE HELMET", punishment: 55, act: "Land Transport (Road User) Rule 2004 11.8" },
  { id: "f60", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O504", name: "BICYCLE HELMET NOT SECURELY FASTENED", punishment: 55, act: "Land Transport (Road User) Rule 2004 11.8" },
  { id: "f61", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O117", name: "NO TAIL LIGHT ON MOPED", punishment: 55, act: "Land Transport (Road User) Rule 2004 11.13" },
  { id: "f62", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O118", name: "NO REAR RED REFLECTOR OR TAPE ON MOPED", punishment: 55, act: "Land Transport (Road User) Rule 2004 11.13" },
  { id: "f63", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "S101", name: "DRIVER FAILED TO WEAR SAFETY HELMET", punishment: 50, demerits: 25, act: "Land Transport (Road User) Rule 2004 7.16" },
  { id: "f64", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "S103", name: "PASSENGER FAILED TO WEAR SAFETY HELMET", punishment: 50, act: "Land Transport (Road User) Rule 2004 7.16" },
  { id: "f65", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V242", name: "MOTO/MOPED FAILED TO USE HEADLAMP DURING DAY", punishment: 100, act: "Land Transport (Road User) Rule 2004 11.14" },
  { id: "f66", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V621", name: "OPERATED MOPED WITHOUT BRAKE ON BOTH WHEELS", punishment: 150, act: "Land Transport (Road User) Rule 2004 11.12" },
  { id: "f67", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V622", name: "OPERATED MOTORCYCLE WITHOUT BRAKE ON BOTH WHEELS", punishment: 150, act: "Land Transport (Road User) Rule 2004 11.12" },
  { id: "f68", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V216", name: "MOTORCYCLE NOT EQUIPPED WITH HEADLAMP", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f69", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V227", name: "NO REAR REFLECTOR ON MOTORCYCLE", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f70", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V306", name: "NO STOP LAMP FITTED ON MOTORCYCLE", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f71", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N332", name: "CARRIED PASSENGER ON MOPED NO PILLION SEAT", punishment: 55, act: "Land Transport (Road User) Rule 2004 11.11" },
  { id: "f72", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D801", name: "FAILED TO GIVE WAY TO A VEHICLE ON THE RIGHT", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 4.1" },
  { id: "f73", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D802", name: "FAILED TO GIVE WAY WHEN TURNING", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 4.2" },
  { id: "f74", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D706", name: "FAILED TO MOVE TO THE LEFT WHEN TURNING LEFT", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.5" },
  { id: "f75", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D707", name: "FAILED TO MOVE TO THE RIGHT WHEN TURNING RIGHT", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.5" },
  { id: "f76", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D708", name: "FAILED TO TURN INTO CORRECT POSITION", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.5" },
  { id: "f77", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F201", name: "FAILED TO STOP AT STOP SIGN", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 4.1" },
  { id: "f78", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F202", name: "FAILED TO GIVE WAY AT STOP SIGN", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 4.1" },
  { id: "f79", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F214", name: "FAILED TO GIVE WAY ENTERING ROUNDABOUT", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 4.6" },
  { id: "f80", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F226", name: "FAILED TO GIVE WAY AT A ONE-WAY GIVE-WAY SIGN", punishment: 100, demerits: 25, act: "Land Transport (Road User) Rule 2004 4.4" },
  { id: "f81", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F301", name: "FAILED TO GIVE WAY AT A GIVE-WAY SIGN", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 4.1" },
  { id: "f82", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F604", name: "ENTERED A BLOCKED INTERSECTION", punishment: 150, act: "Land Transport (Road User) Rule 2004 4.3" },
  { id: "f83", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F605", name: "INCREASED SPEED AT INTERSECTION", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.10" },
  { id: "f84", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D810", name: "FAILED TO GIVE WAY TO ROAD USER ON FOOTPATH", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 4.1" },
  { id: "f85", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D809", name: "TURNED RIGHT AT LIGHTS - FAILED TO GIVE WAY TO LEFT", punishment: 150, act: "Land Transport (Road User) Rule 2004 4.2" },
  { id: "f86", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F106", name: "FAILED TO COMPLY WITH YELLOW TRAFFIC SIGNAL", punishment: 150, act: "Land Transport (Road User) Rule 2004 3.2" },
  { id: "f87", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F110", name: "FAILED TO COMPLY WITH RED TRAFFIC SIGNAL", punishment: 150, act: "Land Transport (Road User) Rule 2004 3.1" },
  { id: "f88", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F112", name: "FAILED TO COMPLY WITH YELLOW ARROW SIGNAL", punishment: 150, act: "Land Transport (Road User) Rule 2004 3.4" },
  { id: "f89", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F113", name: "FAILED TO COMPLY WITH RED ARROW SIGNAL", punishment: 150, act: "Land Transport (Road User) Rule 2004 3.3" },
  { id: "f90", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F118", name: "MADE A PROHIBITED U-TURN", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.13" },
  { id: "f91", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F119", name: "MADE A PROHIBITED LEFT OR RIGHT TURN", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.5" },
  { id: "f92", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F120", name: "FAILED TO COMPLY WITH A NO ENTRY SIGN", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.5" },
  { id: "f93", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F601", name: "FAILED TO COMPLY WITH DIRECTIONAL ARROWS", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.5" },
  { id: "f94", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F218", name: "FAILED TO INDICATE LEFT TURN AT ROUNDABOUT", punishment: 150, act: "Land Transport (Road User) Rule 2004 4.6" },
  { id: "f95", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F219", name: "FAILED TO INDICATE RIGHT TURN AT ROUNDABOUT", punishment: 150, act: "Land Transport (Road User) Rule 2004 4.6" },
  { id: "f96", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "M310", name: "FAILED TO SIGNAL STOPPING", punishment: 150, act: "Land Transport (Road User) Rule 2004 3.10" },
  { id: "f97", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "M311", name: "FAILED TO SIGNAL", punishment: 150, act: "Land Transport (Road User) Rule 2004 3.10" },
  { id: "f98", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "M312", name: "FAILED TO SIGNAL", punishment: 150, act: "Land Transport (Road User) Rule 2004 3.10" },
  { id: "f99", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D810", name: "FAILED TO GIVE WAY TO ROAD USER ON FOOTPATH", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 4.1" },
  { id: "f100", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F103", name: "DRIVER TURNING AT LIGHTS FAILED TO GIVE WAY TO PEDESTRIAN", punishment: 150, act: "Land Transport (Road User) Rule 2004 3.1" },
  { id: "f101", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F121", name: "DRIVER TURNING AT LIGHTS FAILED TO GIVE WAY TO MOBILITY DEVICE", punishment: 150, act: "Land Transport (Road User) Rule 2004 3.1" },
  { id: "f102", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F122", name: "DRIVER TURNING AT LIGHTS FAILED TO GIVE WAY TO RECREATIONAL", punishment: 150, act: "Land Transport (Road User) Rule 2004 3.1" },
  { id: "f103", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F205", name: "ENTERED BLOCKED RAILWAY CROSSING", punishment: 150, act: "Land Transport (Road User) Rule 2004 9.1" },
  { id: "f104", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F220", name: "FAILED TO COMPLY WITH RAIL BARRIER ARMS", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 9.1" },
  { id: "f105", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F221", name: "RISKY CROSSING OF LEVEL CROSSING - VEHICLE", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 9.1" },
  { id: "f106", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F222", name: "FAILED TO STOP FOR RED SIGNAL AT LEVEL CROSSING", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 9.1" },
  { id: "f107", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F401", name: "FAILED TO YEILD RIGHT OF WAY AT PED CROSSING", punishment: 150, demerits: 35, act: "Land Transport (Road User) Rule 2004 10.1" },
  { id: "f108", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F404", name: "BLOCKED A PEDESTRIAN CROSSING", punishment: 150, demerits: 35, act: "Land Transport (Road User) Rule 2004 10.1" },
  { id: "f109", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O202", name: "PEDESTRIAN ON A MOTORWAY", punishment: 250, act: "Land Transport (Road User) Rule 2004 11.10" },
  { id: "f110", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N101", name: "NOISY VEHICLE", punishment: 50, demerits: 25, act: "Land Transport (Road User) Rule 2004 7.4" },
  { id: "f111", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N103", name: "NOISY EQUIPMENT IN A VEHICLE", punishment: 50, demerits: 25, act: "Land Transport (Road User) Rule 2004 7.4" },
  { id: "f112", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N321", name: "OPERATED IN MANNER LIABLE TO CAUSE ANNOYANCE/INJURY", punishment: 600, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f113", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "B404", name: "EQUIPMENT DESIGNED TO INTERFERE WITH SPEED MEASURE", punishment: 150, demerits: 25, act: "Land Transport Act 1998 31" },
  { id: "f114", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D352", name: "POURED SLIPPERY SUBSTANCE ON ROAD", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f115", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D402", name: "SLOW VEHICLE OR INCONSIDERATE DRIVING IMPEDED TRAFFIC", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f116", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D501", name: "CARELESSLY OPENED OR CLOSED DOOR", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.2" },
  { id: "f117", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D727", name: "DROVE ON LAWN, GARDEN OR OTHER CULTIVATION", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f118", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F117", name: "DROVE THE WRONG WAY ON a ONE-WAY ROAD", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f119", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F502", name: "FAILED TO MAKE WAY FOR BLUE-RED BEACONS", punishment: 150, act: "Land Transport (Road User) Rule 2004 5.4" },
  { id: "f120", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "M334", name: "ALIGHTED FROM OR BOARDED A MOVING VEHICLE", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.12" },
  { id: "f121", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N401", name: "UNREASONABLE USE OF A WARNING DEVICE (HORN)", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.4" },
  { id: "f122", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N404", name: "DROVE ON A FOOTPATH", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.13" },
  { id: "f123", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N411", name: "DRIVER USED A MOBILE PHONE WHILE DRIVING", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 7.3A" },
  { id: "f124", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O301", name: "PERMITTED RIDING ON MOTOR VEHICLE IN DANGEROUS POSITION", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 7.9" },
  { id: "f125", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O302", name: "RODE ON A MOTOR VEHICLE IN A DANGEROUS POSITION", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.9" },
  { id: "f126", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V452", name: "OPERATED A MOTOR VEHICLE WITH DOOR OPEN", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.2" },
  { id: "f127", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V494", name: "NOISY EXHAUST (MODIFIED)", punishment: 150, demerits: 25, act: "Land Transport (Road User) Rule 2004 7.4" },
  { id: "f128", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "M304", name: "OPERATING VEHICLE EQUIPPED WITH BELL, SIREN, OR WHISTLE", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.4" },
  { id: "f129", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N201", name: "USED A VEHICLE THAT EMITTED EXCESSIVE SMOKE", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.5" },
  { id: "f130", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N311", name: "PART OF A MOTOR VEHICLE OR LOAD DRAGGED ON ROAD", punishment: 600, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f131", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N318", name: "DANGEROUS CONDITION OF A MOTOR VEHICLE", punishment: 600, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f132", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V402", name: "NO WARNING DEVICE (HORN)", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.4" },
  { id: "f133", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V406", name: "OBSCURED WINDSCREEN", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f134", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V445", name: "OPERATED VEHICLE WITH DAMAGED WINDSCREEN", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f135", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V610", name: "OPERATED VEHICLE WITH UNSAFE SEAT", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f136", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V640", name: "OPERATED VEHICLE WITH UNSOUND SAFETY BELT", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.7" },
  { id: "f137", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V641", name: "OPERATED VEHICLE WITH CUT OR FRAYED SAFETY BELT", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.7" },
  { id: "f138", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V555", name: "NON-APPROVED WHEEL SPACER INSTALLED", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f139", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V556", name: "OPERATED VEHICLE WITH DIFFERENT TYRES ON AN AXLE", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f140", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V557", name: "OPERATED VEHICLE WITH DAMAGED TYRE", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f141", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V561", name: "OPERATED VEHICLE WITH SMOOTH TYRE", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f142", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V563", name: "OPERATED VEHICLE WITH UNSAFE TYRE PRESSURE", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f143", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V417", name: "DEFECTIVE EXHAUST SYSTEM OR SILENCER", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.4" },
  { id: "f144", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V439", name: "USED GLAZING LIKELY TO DAZZLE OR ANNOY", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f145", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V442", name: "OPERATED A MOTOR VEHICLE WITH DARKENED WINDOWS", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f146", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V447", name: "OPERATED MOTOR VEHICLE WITH MODIFIED GLAZING", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f147", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V460", name: "UNSAFE INTERIOR FITTING, CONTROL OR SURFACES", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f148", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V480", name: "USED A VEHICLE WITH A FITTING LIABLE TO CAUSE INJURY", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f149", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V481", name: "PROTRUDING FITTING AFFECTED DRIVER VISION", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f150", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V482", name: "COMPONENT LIKELY TO HOOK PERSON OR VEHICLE", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f151", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V493", name: "EXHAUST SYSTEM NOT TAMPER RESISTANT", punishment: 150, act: "Land Transport (Road User) Rule 2004 7.4" },
  { id: "f152", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V703", name: "OPERATED A MODIFIED VEHICLE THAT WAS NOT CERTIFIED", punishment: 200, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f153", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V131", name: "OPTIONAL LIGHTING EMITTED OTHER THAN DIFFUSE LIGHT", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f154", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V132", name: "OPTIONAL LIGHTING POSITIONED TOO CLOSE TO REQUIRED", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f155", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V133", name: "OPTIONAL LIGHTING FLASHING", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f156", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V134", name: "OPTIONAL LIGHTING REVOLVING", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f157", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V222", name: "DROVE WITHOUT HEADLAMPS ON", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f158", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V230", name: "IMPROPER USE OF HAZARD WARNING LIGHTS", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f159", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V235", name: "UNAUTHORISED USE OF BEACON (HORN)", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f160", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V301", name: "FAILED TO DIP HEADLAMPS FOR OTHER TRAFFIC", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f161", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V309", name: "INAPPROPRIATE USE OF FOG LAMP", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f162", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V311", name: "DAZZLING, CONFUSING OR DISTRACTING LIGHTS", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f163", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V312", name: "POSITION LAMPS NOT ILLUMINATED", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f164", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V202", name: "VEHICLE NOT EQUIPPED WITH HEADLAMPS", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f165", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V204", name: "DISPLAYED OTHER THAN RED OR AMBER LIGHT TO REAR", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f166", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V205", name: "WRONGLY ADJUSTED HEADLIGHTS", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f167", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V218", name: "NO REAR RED REFLECTORS", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f168", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V226", name: "REAR NUMBER PLATE NOT ILLUMINATED", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f169", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V232", name: "DISPLAYED OTHER THAN WHITE/AMBER HEADLAMPS", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f170", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V236", name: "DISPLAYED RED LAMP TO FRONT", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f171", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V240", name: "FORWARD-FACING POSITION LAMP NOT WHITE/AMBER", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f172", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V241", name: "REARWARD-FACING POSITION LAMP NOT RED", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f173", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V305", name: "NO STOP LAMPS FITTED", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f174", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "V308", name: "OPERATED WITHOUT HIGH-MOUNTED STOP LAMP", punishment: 150, act: "Land Transport (Road User) Rule 2004 6.1" },
  { id: "f175", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D701", name: "FAILED TO KEEP TO RIGHT", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 2.1" },
  { id: "f176", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D702", name: "FAILED TO DRIVE ENTIRELY WITHIN LANES", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.3" },
  { id: "f177", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D704", name: "UNSAFE CHANGING OF LANES", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.3" },
  { id: "f178", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D710", name: "DROVE IN LANE OVER CENTRE LINE", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.3" },
  { id: "f179", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D713", name: "WRONG SIDE OF NO PASSING LINE", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.9" },
  { id: "f180", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D715", name: "CUT CORNER TURNING RIGHT", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.5" },
  { id: "f181", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D719", name: "UNAUTHORISED USE OF SPECIAL VEHICLE LANE", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.3" },
  { id: "f182", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D726", name: "DROVE IN EMERGENCY STOPPING LANE (SHOULDER)", punishment: 150, demerits: 10, act: "Land Transport (Road User) Rule 2004 2.3" },
  { id: "f183", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D601", name: "CUT IN WHEN OVERTAKING", punishment: 150, demerits: 35, act: "Land Transport (Road User) Rule 2004 2.9" },
  { id: "f184", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D603", name: "PASSED AT RAILWAY LEVEL CROSSING", punishment: 150, act: "Land Transport (Road User) Rule 2004 9.1" },
  { id: "f185", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D604", name: "PASSING WITH LESS THAN 100M VISIBILITY", punishment: 150, demerits: 35, act: "Land Transport (Road User) Rule 2004 2.9" },
  { id: "f186", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D605", name: "ATTEMPTED TO PASS WITH LESS THAN 100M VISIBILITY", punishment: 150, demerits: 35, act: "Land Transport (Road User) Rule 2004 2.9" },
  { id: "f187", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D610", name: "OVERTOOK ANOTHER VEHICLE - INSUFFICIENT CLEAR ROAD", punishment: 150, demerits: 35, act: "Land Transport (Road User) Rule 2004 2.9" },
  { id: "f188", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D611", name: "OVERTOOK ACROSS FLUSH MEDIAN", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.9" },
  { id: "f189", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D703", name: "FAILED TO KEEP RIGHT OF NO PASSING LINE", punishment: 150, demerits: 35, act: "Land Transport (Road User) Rule 2004 2.9" },
  { id: "f190", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D721", name: "UNSAFE PASSING MANOEUVRE", punishment: 150, demerits: 35, act: "Land Transport (Road User) Rule 2004 2.9" },
  { id: "f191", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D722", name: "INCONSIDERATE PASSING MANOEUVRE", punishment: 150, demerits: 35, act: "Land Transport (Road User) Rule 2004 2.9" },
  { id: "f192", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "D723", name: "UNLAWFULLY PASSED ON THE RIGHT", punishment: 150, act: "Land Transport (Road User) Rule 2004 2.9" },
  { id: "f193", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F402", name: "PASSED VEHICLE STOPPED AT PEDESTRIAN CROSSING", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004 10.1" },
  { id: "f194", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N301", name: "UNSAFE LOADING OF A VEHICLE", punishment: 600, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f195", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N353", name: "OPERATED MOTOR VEHICLE WITH INSECURE LOAD", punishment: 600, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f196", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N511", name: "NO MARKINGS ON LOAD DURING DAYLIGHT", punishment: 370, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f197", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N512", name: "NO LIGHT MARKINGS OVER-WIDTH AT NIGHT", punishment: 370, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f198", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N513", name: "NO LIGHT MARKINGS OVER-LENGTH LOAD", punishment: 370, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f199", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N518", name: "EXCEEDED MAXIMUM FRONT OVERHANG", punishment: 370, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f200", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N524", name: "OPERATED WITH EXCESS REAR OVERHANG", punishment: 370, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f201", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "N536", name: "VEHICLE OR LOAD EXCEEDED WIDTH (OVER 2.5M)", punishment: 370, act: "Land Transport (Road User) Rule 2004 7.1" },
  { id: "f202", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F602", name: "INCORRECTLY ENTERED A MOTORWAY", punishment: 150, act: "Land Transport (Road User) Rule 2004 11.10" },
  { id: "f203", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F608", name: "REVERSED ON MOTORWAY", punishment: 150, act: "Land Transport (Road User) Rule 2004 11.10" },
  { id: "f204", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "O112", name: "USED A CYCLE ON MOTORWAY", punishment: 250, act: "Land Transport (Road User) Rule 2004 11.10" },
  { id: "f205", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "22A(3)", name: "SUSTAINED LOST OF TRACTION", punishment: 600, act: "Land Transport Act 1998 22A", notes: "Incurs immediate 28 day license suspension + Immediate 28-day seizure of the vehicle. " },
  { id: "f206", type: OffenceType.FINE, category: OffenceCategory.TRAFFIC, code: "F220", name: "FAILING TO STOP AT A RED TRAFFIC LIGHT", punishment: 150, demerits: 20, act: "Land Transport (Road User) Rule 2004" }
];